### ISSUE TITLE
Exception on float.Parse

### ISSUE THREAD

**Issue by stanriders** [HoLLy-HaCKeR/OppaiSharp#1]
If your system culture settings don't match osu's beatmap format (for example separator is ',' instead of '.') float parsing will fail with `Input string was not in a correct format.`

**Comment by holly-hacker** [comment]
Yeah, I figured that would be a problem. I'll update it in a sec.

**Comment by holly-hacker** [comment]
Please try latest master branch

**Comment by holly-hacker** [comment]
Assuming fixed.
