### ISSUE TITLE
Exception on PPv2 calc

### ISSUE THREAD

**Issue by stanriders** [HoLLy-HaCKeR/OppaiSharp#2]
[This](https://github.com/HoLLy-HaCKeR/OppaiSharp/blob/master/OppaiSharp/PPCalc.cs#L143) fails when count300 is negative with `Either countObjects or Count300 must be specified`. Example would be inputting an unfinished (failed) score.
oppai-ng is handling this properly.

**Comment by holly-hacker** [comment]
I assume you're using the PPv2Parameters struct. Can you give me some sample code?

**Comment by holly-hacker** [comment]
Please check latest master branch

**Comment by holly-hacker** [comment]
Assuming fixed
