### ISSUE TITLE
Can't calculate pp when c100 >= beatmap circles

### ISSUE THREAD

**Issue by ColdVolcano** [HoLLy-HaCKeR/OppaiSharp#3]
when doing the example program on README.md, but instead of passing c100: 8 we pass `c100: beatmap.CountCircles` the resulting pp will be of a 100% acc play

Alternatively, if a value higher than beatmap.CountCircles is passed `Either countObjects or Count300 must be specified` will be thrown

Tested with https://osu.ppy.sh/b/706711

**Comment by holly-hacker** [comment]
Probably same issue as #2.

**Comment by holly-hacker** [comment]
Please check latest master branch

**Comment by ColdVolcano** [comment]
Half problem fixed, if c100 equals beatmap object count acc will be calculated as 100% instead of 33.33%, same with c50 (16.66 -> 100%)

**Comment by ColdVolcano** [comment]
To make matters worse, seems like accuracy pp values are wrong if c100 or c50 >= objectcount
